/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRollSystem;

import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author albertzkiki
 */
public class Employee extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employee
     */
    Connection conn =null;
    PreparedStatement pst= null;
    Statement stm = null;
    ResultSet rs = null;
    public int regno = 0;
    String var = "";
     String code = "BD00220";
     private String gender;
     
     
        
    public Employee() {
        initComponents();
        RegNoGenerator();
    }
    
    public void updateSave(String QUERRY) {
        try {
            
            connection connect = new connection();
            conn = (Connection)connect.Connectdb();
            pst = conn.prepareStatement(QUERRY);
            pst.execute();
            //conn.close();
            
        } catch (SQLException e) {
            
          JOptionPane.showMessageDialog(null, e);
          
        }

   }
    
    public void clear(){
        
        employeeid.setText(" ");
        firstname.setText(" ");
        surname.setText(" ");
        email.setText(" ");
        contacts.setText(" ");
        address.setText("");
        house.setText("");
        postcode.setText("");
        jlabelimage.setIcon(null);
        imagepath.setText("");
        department.setSelectedIndex(0);
        salary.setText("");
        ssn.setText(null);
        id.setText("");
        
    }
    
    public void RegNoGenerator(){
        
        Date curDate = new Date();
        SimpleDateFormat format = new SimpleDateFormat("YYYY");
        String datetostring = format.format(curDate);
        int year = Integer.parseInt(datetostring) % 100;
        
        connection connect = new connection();
        conn = (Connection)connect.Connectdb();
        
        String sql = "SELECT LastRegNo FROM registrationmonitoring";
        
        try {
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if(rs.next()){
                
                String add = rs.getString("LastRegNo");
                int add1 = Integer.parseInt(add);
                
                regno = add1 + 1;
                
                if(regno < 10){
                    var ="000";
                }
                if(regno > 10 && regno<100){
                    var="00";
                }
                if(regno >100 && regno<1000){
                    var="0";
                }
                employeeid.setText(code+year+var+regno);
                
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
//    public void addtodatabase(){
//        
//        connection connect = new connection();
//        conn = (Connection)connect.Connectdb();
//        
//        try {
//            
//            String sql1="INSERT * INTO "
//            
//            
//        } catch (Exception e) {
//        }
//        
//        
//    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        firstname = new javax.swing.JTextField();
        employeeid = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        surname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        contacts = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        address = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        house = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        postcode = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jlabelimage = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        imagepath = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        loadimagebtn = new javax.swing.JButton();
        department = new javax.swing.JComboBox<>();
        salary = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        ssn = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JSeparator();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Registration");

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Employee ID :");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("FirstName :");

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("SurName :");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Date Of Birth :");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Gender :");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Email :");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Contacts :");

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Address :");

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Apt/House No :");

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Post Code :");

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Date Hired :");

        firstname.setBackground(getBackground());
        firstname.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(255, 255, 255));
        firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstname.setBorder(null);
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnameKeyTyped(evt);
            }
        });

        employeeid.setEditable(false);
        employeeid.setBackground(getBackground());
        employeeid.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        employeeid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        employeeid.setBorder(null);

        surname.setBackground(getBackground());
        surname.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        surname.setForeground(new java.awt.Color(255, 255, 255));
        surname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        surname.setBorder(null);
        surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                surnameKeyTyped(evt);
            }
        });

        email.setBackground(getBackground());
        email.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(null);

        contacts.setBackground(getBackground());
        contacts.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        contacts.setForeground(new java.awt.Color(255, 255, 255));
        contacts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contacts.setBorder(null);
        contacts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactsKeyTyped(evt);
            }
        });

        address.setBackground(getBackground());
        address.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setBorder(null);
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addressKeyTyped(evt);
            }
        });

        house.setBackground(getBackground());
        house.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        house.setForeground(new java.awt.Color(255, 255, 255));
        house.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        house.setBorder(null);
        house.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                houseKeyTyped(evt);
            }
        });

        postcode.setBackground(getBackground());
        postcode.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        postcode.setForeground(new java.awt.Color(255, 255, 255));
        postcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        postcode.setBorder(null);
        postcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                postcodeKeyTyped(evt);
            }
        });

        r_male.setBackground(getBackground());
        r_male.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        r_male.setForeground(new java.awt.Color(255, 255, 255));
        r_male.setSelected(true);
        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });

        r_female.setBackground(getBackground());
        r_female.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        r_female.setForeground(new java.awt.Color(255, 255, 255));
        r_female.setSelected(true);
        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });

        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jDesktopPane2.setLayer(jlabelimage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelimage, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabelimage, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("image path :");

        imagepath.setEditable(false);
        imagepath.setBackground(getBackground());
        imagepath.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        imagepath.setForeground(new java.awt.Color(255, 255, 255));
        imagepath.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        imagepath.setBorder(null);

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Department :");

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Salary :");

        loadimagebtn.setBackground(new java.awt.Color(255, 255, 255));
        loadimagebtn.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        loadimagebtn.setText("Load Image");
        loadimagebtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        loadimagebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadimagebtnActionPerformed(evt);
            }
        });

        department.setBackground(getBackground());
        department.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        department.setForeground(new java.awt.Color(255, 255, 255));
        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose one--", "--Human Resourse--", "--ICT--", "--Accoutant--", "--Treasury--", "--Manager--", "--Credit Analyst--", "--Administrator--" }));
        department.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departmentItemStateChanged(evt);
            }
        });
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        salary.setEditable(false);
        salary.setBackground(getBackground());
        salary.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        salary.setForeground(new java.awt.Color(255, 255, 255));
        salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        salary.setBorder(null);

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("ID :");

        ssn.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        ssn.setForeground(new java.awt.Color(255, 255, 255));
        ssn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ssn.setBorder(null);
        ssn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ssnKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("SSN :");

        id.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.setBorder(null);
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        save.setText("Save");
        save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        add.setText("New");
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        update.setText("Update");
        update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        delete.setText("Clear");
        delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        jDateChooser2.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(firstname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(employeeid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(surname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(contacts, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(address, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(house, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(postcode, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(r_male, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(r_female, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(imagepath, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(loadimagebtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(department, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(salary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ssn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(save, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(add, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(update, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(delete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDateChooser1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDateChooser2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstname)
                    .addComponent(jSeparator4)
                    .addComponent(surname)
                    .addComponent(email)
                    .addComponent(jSeparator6)
                    .addComponent(contacts)
                    .addComponent(jSeparator7)
                    .addComponent(address)
                    .addComponent(jSeparator8)
                    .addComponent(house)
                    .addComponent(jSeparator9)
                    .addComponent(postcode)
                    .addComponent(jSeparator10)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(r_male)
                        .addGap(31, 31, 31)
                        .addComponent(r_female))
                    .addComponent(employeeid)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(loadimagebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                        .addComponent(imagepath)))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(salary))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator12)
                                        .addComponent(jSeparator13)
                                        .addComponent(ssn))))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator16)
                                    .addComponent(id))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(employeeid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(7, 7, 7)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(r_male)
                                    .addComponent(r_female)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loadimagebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagepath, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(house, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        clear();
        RegNoGenerator();
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      
        // dispose();
         clear();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            if(firstname.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Firstname field  is empty","error",JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(surname.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Surname field  is empty","error",JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText().equals("")){
            JOptionPane.showMessageDialog(this,"Insert Date of Birth","error",JOptionPane.ERROR_MESSAGE);
            return;
       }
       if(department.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(this, "please select the department assigned","Error",JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(email.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Insert an email address","error",JOptionPane.ERROR_MESSAGE);
           return;
       }
       if(contacts.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Insert your contacts","error",JOptionPane.ERROR_MESSAGE);
            return;
       }
       if(house.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Insert your apt/house number","error",JOptionPane.ERROR_MESSAGE);
            return;
       }
       if(postcode.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Insert your postal code address","error",JOptionPane.ERROR_MESSAGE);
            return;
       }
       if(((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText().equals("")){
            JOptionPane.showMessageDialog(this,"date field is empty","error",JOptionPane.ERROR_MESSAGE);
            return;
       }
       if(imagepath.getText().equals("")){
            JOptionPane.showMessageDialog(this,"please load your image","error",JOptionPane.ERROR_MESSAGE);
            return;
       }
       if(department.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this,"Choose your department","error",JOptionPane.ERROR_MESSAGE);
            return;
       }
       if(ssn.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Insert your social security number","error",JOptionPane.ERROR_MESSAGE);
            return;
       }
       if(id.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Insert Date of Birth","error",JOptionPane.ERROR_MESSAGE);
            return;
       }
       
       connection connect = new connection();
       conn = (Connection)connect.Connectdb();
       
            try {
                String sql2 = "INSERT INTO `employeeregistartion`(`Employeeid`,`Firstname`,`Surname`,`Gender`,`Email`,`Contacts`,`House`,"
                        + "`Postcode`,`Datehired`,`Imagepath`,`Department`,`Salary`,`SSN`,`Id`,`Address`,`DOB`) VALUES('"+employeeid.getText()+"',"
                        + "'"+firstname.getText()+"','"+surname.getText()+"','"+gender+"',"
                        + "'"+email.getText()+"','"+contacts.getText()+"','"+house.getText()+"',"
                        + "'"+postcode.getText()+"','"+((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText()+"','"+imagepath.getText()+"',"
                        + "'"+department.getSelectedItem()+"','"+salary.getText()+"','"+ssn.getText()+"',"
                        + "'"+id.getText()+"','"+address.getText()+"','"+((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText()+"')";
                
               
               
               String sql3="UPDATE `registrationmonitoring` SET  lastRegNo='"+regno+"' WHERE staff=1";
               
               
               String dept = (String) department.getSelectedItem();
                
               String sql22 = "INSERT INTO `imagesbd`(`Employeeid`,`Firstname`,`Surname`,`Department`,`images`) "
                        + "VALUES('"+employeeid.getText()+"','"+firstname.getText()+"','"+surname.getText()+"'"
                        + ",'"+dept+"','"+person_image+"')";
                    
                updateSave(sql22);
                updateSave(sql3);
                
                pst = conn.prepareStatement(sql2);     
                pst.execute();
                   
                
                
                   JOptionPane.showMessageDialog(null, "Employee registed successfully","Employees Record",JOptionPane.INFORMATION_MESSAGE);
               
            }catch (Exception e) {
                
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            
        }catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,e.getMessage());
            
        }
        
        
       // clear();
        RegNoGenerator();
        
        
       
    }//GEN-LAST:event_saveActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        gender = "male";
        r_male.setSelected(true);
        r_female.setSelected(false);
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        gender = "female";
        r_male.setSelected(false);
        r_female.setSelected(true);
    }//GEN-LAST:event_r_femaleActionPerformed

    private void firstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyTyped
       char c = evt.getKeyChar();
       
       if(!((c>='a' && c<='z') ||(c>='A' && c<='Z') || (c == KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_TAB))){
           getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(this, "Enter alphabets only","warning",JOptionPane.WARNING_MESSAGE);
           
           int length = firstname.getText().length();
           
           if(length >=20){
               getToolkit().beep();
               evt.consume();
           }
       }
    }//GEN-LAST:event_firstnameKeyTyped

    private void surnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameKeyTyped
       char c = evt.getKeyChar();
       
       if(!((c>='a' && c<='z') ||(c>='A' && c<='Z') || (c == KeyEvent.VK_BACKSPACE) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_TAB))){
           getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(this, "Enter alphabets only","warning",JOptionPane.WARNING_MESSAGE);
           
           int length = firstname.getText().length();
           
           if(length >=20){
               getToolkit().beep();
               evt.consume();
           }
       }
    }//GEN-LAST:event_surnameKeyTyped

    private void contactsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactsKeyTyped
       char c = evt.getKeyChar();
       
       if(!( (c>='0' && c <='9') || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_TAB )){
           
           getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(this, "Enter numerics only","WARNING",JOptionPane.WARNING_MESSAGE);
           
           int length = contacts.getText().length();
           if(length >12){
               getToolkit().beep();
               evt.consume();
           }
       }
       
    }//GEN-LAST:event_contactsKeyTyped

    private void addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyTyped
        char c = evt.getKeyChar();
       
       if(!( (c>='0' && c <='9') || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_TAB )){
           
           getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(this, "Enter numerics only","WARNING",JOptionPane.WARNING_MESSAGE);
           
           int length = address.getText().length();
           if(length >12){
               getToolkit().beep();
               evt.consume();
           }
       }
    }//GEN-LAST:event_addressKeyTyped

    private void houseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_houseKeyTyped
       char c = evt.getKeyChar();
       
       if(!( (c>='0' && c <='9') || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_TAB )){
           
           getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(this, "Enter numerics only","WARNING",JOptionPane.WARNING_MESSAGE);
           
           int length = house.getText().length();
           if(length >12){
               getToolkit().beep();
               evt.consume();
           }
       }
    }//GEN-LAST:event_houseKeyTyped

    private void postcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postcodeKeyTyped
       char c = evt.getKeyChar();
       
       if(!( (c>='0' && c <='9') || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_TAB )){
           
           getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(this, "Enter numerics only","WARNING",JOptionPane.WARNING_MESSAGE);
           
           int length = postcode.getText().length();
           if(length >12){
               getToolkit().beep();
               evt.consume();
           }
       }
    }//GEN-LAST:event_postcodeKeyTyped

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        
       
        
        
    }//GEN-LAST:event_departmentActionPerformed

    private void departmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departmentItemStateChanged
         int dept = department.getSelectedIndex();
        
        if(dept == 0){
            salary.setText(" ");
        }
        else if (dept == 1){
            salary.setText("20000");
        }
        else if (dept == 2){
            salary.setText("50000");
        }
        else if (dept == 3){
            salary.setText("25000");
        }
        else if (dept == 4){
            salary.setText("40000");
        }
        else if (dept == 5){
            salary.setText("55000");
        }
        else if (dept == 6){
            salary.setText("60000");
        }
        
        
    }//GEN-LAST:event_departmentItemStateChanged

    private void ssnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssnKeyTyped
       
        char c = evt.getKeyChar();
       
       if(!( (c>='0' && c <='9') || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_TAB )){
           
           getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(this, "Enter numerics only","WARNING",JOptionPane.WARNING_MESSAGE);
           
           int length = ssn.getText().length();
           if(length >12){
               getToolkit().beep();
               evt.consume();
           }
       }
    }//GEN-LAST:event_ssnKeyTyped

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
       char c = evt.getKeyChar();
       
       if(!( (c>='0' && c <='9') || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_TAB )){
           
           getToolkit().beep();
           evt.consume();
           JOptionPane.showMessageDialog(this, "Enter numerics only","WARNING",JOptionPane.WARNING_MESSAGE);
           
           int length = id.getText().length();
           if(length >12){
               getToolkit().beep();
               evt.consume();
           }
       }
    }//GEN-LAST:event_idKeyTyped

    private void loadimagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadimagebtnActionPerformed
        ImageIcon format = null;
        JFileChooser jchooser = new JFileChooser();
        jchooser.setDialogTitle("Se+arch image path");
        jchooser.showOpenDialog(null);
        File f = jchooser.getSelectedFile();
                  filename = f.getAbsolutePath();
              //Creating an ImageIcon out of the selected file
                ImageIcon image = new ImageIcon(f.getAbsolutePath());
                // Get width and height of picture Label
                java.awt.Rectangle rect = jlabelimage.getBounds();
                //    // Scaling the Image to fit in the picture Label
                Image scaledImage = image.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
                // Converting the image back to ImageIcon to make it acceptable by picture Label
                image = new ImageIcon(scaledImage);
                jlabelimage.setIcon(image);
                filename = f.getAbsolutePath();
               imagepath.setText(filename);


       try{
            File image1=new File (filename);
            FileInputStream fis=new FileInputStream(image1);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte [] buf=new byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf, 0, readNum);
            }
           person_image=bos.toByteArray();//converts image to binary string of array
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loadimagebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contacts;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JTextField email;
    private javax.swing.JTextField employeeid;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField house;
    private javax.swing.JTextField id;
    private javax.swing.JTextField imagepath;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jlabelimage;
    private javax.swing.JButton loadimagebtn;
    private javax.swing.JTextField postcode;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField salary;
    private javax.swing.JButton save;
    private javax.swing.JTextField ssn;
    private javax.swing.JTextField surname;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    String filename = null;
    byte [] person_image = null;


}