/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRollSystem;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
//import javax.swing.text.Document;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.util.Date;



/**
 *
 * @author albertzkiki
 */
public class PaySlip extends javax.swing.JInternalFrame {

    /**
     * Creates new form Allowance
     */
    
    Connection conn = null;
    ResultSet rs = null;
    Statement stm = null;
    PreparedStatement pst = null;
    
    
    public PaySlip() {
        initComponents();
       
    }

    
    public void updateSave(String QUERRY) {
        try {
            
            connection connect = new connection();
            conn = (Connection)connect.Connectdb();
            pst = conn.prepareStatement(QUERRY);
            pst.execute();
            //conn.close();
            
        } catch (SQLException e) {
            
          JOptionPane.showMessageDialog(null, e);
          
        }

   }
    
    
    public void clear(){
        
        empid.setText("");
        employeeid.setText("");
        firstname.setText("");
        surname.setText("");
        email.setText("");
        contacts.setText("");
        address.setText("");
        ssn.setText("");
        department.setText("");
        basicsalary.setText("");
        allowance.setText("");
        netsalary.setText("");
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        employeeid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        contacts = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        basicsalary = new javax.swing.JTextField();
        ssn = new javax.swing.JTextField();
        allowance = new javax.swing.JTextField();
        netsalary = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "Payslips Generation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment");

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Employee ID:");

        employeeid.setBackground(getBackground());
        employeeid.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        employeeid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        employeeid.setBorder(null);
        employeeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                employeeidKeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-Search-20.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("FirstName:");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Employee ID:");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Address:");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Contacts:");

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("SurName");

        empid.setEditable(false);
        empid.setBackground(getBackground());
        empid.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        empid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        empid.setBorder(null);

        email.setEditable(false);
        email.setBackground(getBackground());
        email.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(null);

        surname.setEditable(false);
        surname.setBackground(getBackground());
        surname.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        surname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        surname.setBorder(null);

        firstname.setEditable(false);
        firstname.setBackground(getBackground());
        firstname.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstname.setBorder(null);

        contacts.setEditable(false);
        contacts.setBackground(getBackground());
        contacts.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        contacts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contacts.setBorder(null);

        address.setEditable(false);
        address.setBackground(getBackground());
        address.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("SSN:");

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Department:");

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Basic Salary:");

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Net Salary:");

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Allowances:");

        department.setEditable(false);
        department.setBackground(getBackground());
        department.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        department.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        department.setBorder(null);

        basicsalary.setEditable(false);
        basicsalary.setBackground(getBackground());
        basicsalary.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        basicsalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        basicsalary.setBorder(null);
        basicsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicsalaryActionPerformed(evt);
            }
        });

        ssn.setEditable(false);
        ssn.setBackground(getBackground());
        ssn.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        ssn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ssn.setBorder(null);
        ssn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ssnKeyReleased(evt);
            }
        });

        allowance.setEditable(false);
        allowance.setBackground(getBackground());
        allowance.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        allowance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        allowance.setBorder(null);
        allowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowanceActionPerformed(evt);
            }
        });
        allowance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                allowanceKeyReleased(evt);
            }
        });

        netsalary.setEditable(false);
        netsalary.setBackground(getBackground());
        netsalary.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        netsalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        netsalary.setBorder(null);
        netsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                netsalaryKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton1.setText("Calculate");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton2.setText("Generate Payslip");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(employeeid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(empid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(email, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(surname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(firstname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(contacts, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(address, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(department, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(basicsalary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ssn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(allowance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(netsalary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(451, 451, 451))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(employeeid, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(surname)
                            .addComponent(empid)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator5)
                            .addComponent(contacts)
                            .addComponent(address)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator7)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(168, 168, 168)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator12)
                            .addComponent(jSeparator11)
                            .addComponent(jSeparator10)
                            .addComponent(jSeparator9)
                            .addComponent(department)
                            .addComponent(basicsalary, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(ssn)
                            .addComponent(allowance)
                            .addComponent(netsalary)
                            .addComponent(jSeparator8))))
                .addGap(110, 110, 110))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(employeeid, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(empid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                                    .addComponent(jSeparator9)))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(basicsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allowance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(contacts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(netsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeidKeyReleased

        connection connect = new connection();
        conn = (Connection)connect.Connectdb();
        
        try {
            
            String sql = "SELECT * FROM `employeeregistartion` WHERE Employeeid='"+employeeid.getText()+"'";
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if(rs.next()){
            
                String id =  rs.getString("Employeeid");
                String fname = rs.getString("Firstname");
                String sname = rs.getString("Surname");
                String contact = rs.getString("Contacts");
                String mail = rs.getString("Email");
                String adress = rs.getString("Address");
                String ssnn = rs.getString("SSN");
                String dept = rs.getString("Department");
                String bsalary = rs.getString("Salary");
                
                empid.setText(id);
                firstname.setText(fname);
                surname.setText(sname);
                contacts.setText(contact);
                email.setText(mail);
                address.setText(adress);
                ssn.setText(ssnn);
                department.setText(dept);
                basicsalary.setText(bsalary);
            
            }
            
            
//            String sql1 = "SELECT * FROM `allowance` WHERE Employeeid='"+employeeid.getText()+"'";
//            
//            pst = conn.prepareCall(sql1);
//            rs = pst.executeQuery();
//            
//            String allowances = rs.getString("TotalPay");
//            allowance.setText(allowances);
            
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_employeeidKeyReleased

    private void basicsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicsalaryActionPerformed

    private void ssnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ssnKeyReleased

    }//GEN-LAST:event_ssnKeyReleased

    private void allowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allowanceActionPerformed

    private void allowanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_allowanceKeyReleased
       
       
    }//GEN-LAST:event_allowanceKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        connection connect = new connection();
        conn = (Connection)connect.Connectdb();
        
        
        try {
          
            
        String sql2 = "SELECT * FROM `allowance` WHERE Employeeid='"+employeeid.getText()+"'";
        
        pst = conn.prepareStatement(sql2);
        rs = pst.executeQuery();
        
        if(rs.next()){
            
        String e = rs.getString("TotalPay");
        allowance.setText(e);
        
        int a = Integer.parseInt(basicsalary.getText());
        int b = Integer.parseInt(allowance.getText());
        
        int c = a+b;
        
        String d = String.valueOf(c);
        netsalary.setText(d);
        
        }else{
            
            JOptionPane.showMessageDialog(null, firstname.getText()+ "does not have any Allowance");
            
            int z = 0;
            allowance.setText(String.valueOf(z));
            
        }
        
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        connection connect = new connection();
        conn = (Connection)connect.Connectdb();
        
        
        if(empid.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Search for a specific employee first","Error",JOptionPane.ERROR_MESSAGE);
            
        }
        if(allowance.getText().equals("")){
            
             JOptionPane.showMessageDialog(this, "Calculate the Employees allowance in order to generate slip","Error",JOptionPane.ERROR_MESSAGE);
        }
        if(netsalary.getText().equals("")){
            
             JOptionPane.showMessageDialog(this, "Calculate the Employees netsalary in order to generate slip","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        
        
        String id = empid.getText();
        String fname = firstname.getText();
        String sname = surname.getText();
        String mail = email.getText();
        String contact = contacts.getText();
        String adress = address.getText();
        String ssnn = ssn.getText();
        String bsalary = basicsalary.getText();
        String allowances = allowance.getText();
        String nsalary = netsalary.getText();
        String dpt = department.getText();
        
        
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File(fname+" "+sname+" "+"PaySlip"+".pdf"));
        
        int dialogResult = dialog.showSaveDialog(null);
        
        if (dialogResult == JFileChooser.APPROVE_OPTION){
            
            String filepath = dialog.getSelectedFile().getPath();
            
            
        
            
            try {
                
                String sql =  "SELECT * FROM `allowance` WHERE Employeeid = '"+id+"'";
                 
                pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
                  
                    if(rs.next()){
                    String  OT = rs.getString(8);
                    String med = rs.getString(9);
                    String  bon = rs.getString(10);
                    String oth = rs.getString(11);
                    String all = rs.getString(12);
                    
                    int allo = Integer.parseInt(all);
                    int bsalo =Integer.parseInt(bsalary);
                    
                    
                    

                    String sql1 = "SELECT * FROM `salarydeduction` WHERE Employeeid='"+id+"'";
                    pst = conn.prepareStatement(sql1);
                    rs = pst.executeQuery();
                    
                    int tax = 15;
                    
                    int tx = Integer.parseInt(bsalary);
                    int cal = tx/100*tax;
                    String a = String.valueOf(cal);
                    
                    int nssf = 1000;
                    
                  
                    
                    if(rs.next()){
                
                    String  TD = rs.getString(8);
                    String res = rs.getString(10);
                    
                    int y = Integer.parseInt(TD);
                    
                    int totalDed = nssf+cal+y;
                    
                    
                    int net = bsalo+allo-totalDed;
                
                 Document mydocument = new Document();
                 PdfWriter myWriter = PdfWriter.getInstance(mydocument, new FileOutputStream(filepath));
                 
                 mydocument.open();
                 mydocument.add(new Paragraph ("PAY SLIP",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                 mydocument.add(new Paragraph(new Date().toString()));
                 mydocument.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                 mydocument.add(new Paragraph("Employee Details",FontFactory.getFont(FontFactory.TIMES_BOLD,16,Font.BOLD)));
                 mydocument.add(new Paragraph("Name of Emloyee:"+fname+" "+sname,FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Email                   :"+mail,FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Contacts              : "+contact,FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Address              : "+adress,FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Department           : "+dpt,FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("SSN                   : "+ssnn,FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                 mydocument.add(new Paragraph("Salaries",FontFactory.getFont(FontFactory.TIMES_BOLD,16,Font.BOLD)));
                 mydocument.add(new Paragraph("Basic Salary :"+bsalary+".00Ksh",FontFactory.getFont(FontFactory.TIMES_BOLD,14)));
                 mydocument.add(new Paragraph("Overtime :"+OT+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Medical :"+med+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Bonus: "+bon+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Others: "+oth+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Total Allowances: "+all+".00Ksh",FontFactory.getFont(FontFactory.TIMES_BOLD,14)));
                 mydocument.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                 mydocument.add(new Paragraph("Deductions",FontFactory.getFont(FontFactory.TIMES_BOLD,16,Font.BOLD)));
                 mydocument.add(new Paragraph("Deduction: "+TD+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Reason: "+res,FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Tax Rate: "+tax+"%",FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Tax: "+a+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("NSSF: "+nssf+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14)));
                 mydocument.add(new Paragraph("Total Deduction"+totalDed+".00Ksh",FontFactory.getFont(FontFactory.TIMES_BOLD,14)));
                 mydocument.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                 mydocument.add(new Paragraph("Total Pay",FontFactory.getFont(FontFactory.TIMES_BOLD,16,Font.BOLD)));
                 mydocument.add(new Paragraph("Basic Salary: "+bsalary+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD)));
                 mydocument.add(new Paragraph("Total Allowance: "+all+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD)));
                 mydocument.add(new Paragraph("Total Deduction: "+totalDed+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD)));
                 mydocument.add(new Paragraph("Net Salary: "+net+".00Ksh",FontFactory.getFont(FontFactory.TIMES_ROMAN,14,Font.BOLD)));
                 mydocument.close();
                
                JOptionPane.showMessageDialog(null, "Report successfully Generated");
                
                
                    }
                
                    }
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, e);
                
            }
             
        }
        
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        clear();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void netsalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_netsalaryKeyReleased

    }//GEN-LAST:event_netsalaryKeyReleased

    private void jButton1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField allowance;
    private javax.swing.JTextField basicsalary;
    private javax.swing.JTextField contacts;
    private javax.swing.JTextField department;
    private javax.swing.JTextField email;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField employeeid;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField netsalary;
    private javax.swing.JTextField ssn;
    private javax.swing.JTextField surname;
    // End of variables declaration//GEN-END:variables
}
