/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRollSystem;

import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author albertzkiki
 */
public class Reports extends javax.swing.JInternalFrame {

    
    Connection conn = null;
    ResultSet rs = null;
    Statement stm = null;
    PreparedStatement pst = null;
    
    public Reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        choosereport = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "Reports", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(255, 204, 0))); // NOI18N

        jPanel1.setBackground(getBackground());
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "Report Panel", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(255, 204, 0))); // NOI18N

        jLabel1.setBackground(getBackground());
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Select Report");

        choosereport.setBackground(getBackground());
        choosereport.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        choosereport.setForeground(new java.awt.Color(255, 255, 255));
        choosereport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose One to Generate--", "--Employees full Report--", "--Employees Total Allowance--", "--Employee total Increase--", "--Employee total deductions--", " " }));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Preview");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Generate");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(choosereport, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choosereport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(getBackground());
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "Report Preview", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(255, 204, 0))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        choosereport.setSelectedIndex(0);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        connection connect = new connection();
        conn = (Connection)connect.Connectdb();
        
        try {
            
              if(choosereport.getSelectedIndex()==0){
          
                  JOptionPane.showMessageDialog(null,"Please Select a report to be Generated","Error",JOptionPane.ERROR_MESSAGE);
                  
                }
              if(choosereport.getSelectedIndex()== 1){

                  JFileChooser dialog = new JFileChooser();
                  dialog.setSelectedFile(new File("Employees Full Report"+".pdf"));
                  
                  int dialogResult = dialog.showSaveDialog(null);
                  
                  if(dialogResult == JFileChooser.APPROVE_OPTION){
                      
                      String filepath = dialog.getSelectedFile().getPath();
                      
                      try {
                          
                          String sql = "SELECT * FROM `employeeregistartion`";
                         
                          pst = conn.prepareCall(sql);
                          rs = pst.executeQuery();
                                              
                          
                          Document mydoc = new Document(PageSize.A4.rotate());
                          PdfWriter myWriter = PdfWriter.getInstance(mydoc, new FileOutputStream(filepath));
                          PdfPTable table = new PdfPTable(15);
                          
                          mydoc.open();
                          
                          float[] ColumnWidth = new float[]{9,7,7,6,8,7,5,6,8,9,8,8,8,8,8};
                          table.setWidths(ColumnWidth);
                          table.setWidthPercentage(100);
                          
                          
                          mydoc.add(new Paragraph("Employee Full Report",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          mydoc.add(new Paragraph(new Date().toString(),FontFactory.getFont(FontFactory.TIMES_BOLD,17,Font.BOLD)));
                          mydoc.add(new Paragraph(" ",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          mydoc.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                          mydoc.add(new Paragraph(" ",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          
                          table.addCell(new PdfPCell(new Paragraph("Employeeid",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Firstname",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Surname",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Gender",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Email",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Contacts",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("House",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Postcode",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("DateHired",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Department",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Salary",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("SSN",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Id No.",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Address",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Date of Birth",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                           
                           
                          while(rs.next()){
                              
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));    
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(5),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(8),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(9),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(11),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(12),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(13),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(14),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(15),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(16),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          
                          }
                          
                          mydoc.add(table);
                          
                          mydoc.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                          
                          mydoc.close();
                          
                          JOptionPane.showMessageDialog(null, "Report Generated Successfully");
                          
                          
                      } catch (Exception e) {
                          
                          JOptionPane.showMessageDialog(null, e);
                      }
                      
                   
                      
                  }
                
              }
              if(choosereport.getSelectedIndex()==2){
                                    
                   JFileChooser dialog = new JFileChooser();
                  dialog.setSelectedFile(new File("Employees Full Report"+".pdf"));
                  
                  int dialogResult = dialog.showSaveDialog(null);
                  
                  if(dialogResult == JFileChooser.APPROVE_OPTION){
                      
                      String filepath = dialog.getSelectedFile().getPath();
                      
                      try {
                          
                          String sql = "SELECT * FROM `allowance`";
                         
                          pst = conn.prepareCall(sql);
                          rs = pst.executeQuery();
                                              
                          
                          Document mydoc = new Document(PageSize.A4.rotate());
                          PdfWriter myWriter = PdfWriter.getInstance(mydoc, new FileOutputStream(filepath));
                          PdfPTable table = new PdfPTable(12);
                          
                          mydoc.open();
                          
                          float[] ColumnWidth = new float[]{9,7,7,6,8,7,5,6,8,9,8,8};
                          table.setWidths(ColumnWidth);
                          table.setWidthPercentage(100);
                          
                          
                          mydoc.add(new Paragraph("Employee Allowance Full Report",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          mydoc.add(new Paragraph(new Date().toString(),FontFactory.getFont(FontFactory.TIMES_BOLD,17,Font.BOLD)));
                          mydoc.add(new Paragraph(" ",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          mydoc.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                          mydoc.add(new Paragraph(" ",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          
                          table.addCell(new PdfPCell(new Paragraph("Employeeid",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Firstname",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Surname",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Department",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Salary",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("SSN",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Overtime",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("TotalOvertime",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Medical",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Bonus",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Others",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("TotalPay",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));                       
                           
                          while(rs.next()){
                              
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));    
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(5),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(8),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(9),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(10),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(11),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(12),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          }
                          
                          mydoc.add(table);
                          
                          mydoc.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                          
                          mydoc.close();
                          
                          JOptionPane.showMessageDialog(null, "Report Generated Successfully");
                          
                          
                      } catch (Exception e) {
                          
                          JOptionPane.showMessageDialog(null, e);
                      }
                      
                   
                      
                  }
                  
              }
              if(choosereport.getSelectedIndex()==3){
                 
                  JFileChooser dialog = new JFileChooser();
                  dialog.setSelectedFile(new File("Employees Salaryincrease Full Report"+".pdf"));
                  
                  int dialogResult = dialog.showSaveDialog(null);
                  
                  if(dialogResult == JFileChooser.APPROVE_OPTION){
                      
                      String filepath = dialog.getSelectedFile().getPath();
                      
                      try {
                          
                          String sql = "SELECT * FROM `salaryincrease`";
                         
                          pst = conn.prepareCall(sql);
                          rs = pst.executeQuery();
                                              
                          
                          Document mydoc = new Document(PageSize.A4.rotate());
                          PdfWriter myWriter = PdfWriter.getInstance(mydoc, new FileOutputStream(filepath));
                          PdfPTable table = new PdfPTable(10);
                          
                          mydoc.open();
                          
                          float[] ColumnWidth = new float[]{9,7,7,6,8,7,5,6,8,9};
                          table.setWidths(ColumnWidth);
                          table.setWidthPercentage(100);
                          
                          
                          mydoc.add(new Paragraph("Employee Salaryincrease Full Report",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          mydoc.add(new Paragraph(new Date().toString(),FontFactory.getFont(FontFactory.TIMES_BOLD,17,Font.BOLD)));
                          mydoc.add(new Paragraph(" ",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          mydoc.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                          mydoc.add(new Paragraph(" ",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          
                          table.addCell(new PdfPCell(new Paragraph("Employeeid",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Firstname",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Surname",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Department",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Salary",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Dste",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Percent/Amount",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("TotalIncrease",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Newsalary",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Reason",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                           
                          while(rs.next()){
                              
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));    
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(5),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(8),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(9),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(10),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                       
                          }
                          
                          
                          
                          mydoc.add(table);
                          
                          mydoc.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                          
                          mydoc.close();
                          
                          JOptionPane.showMessageDialog(null, "Report Generated Successfully");
                          
                          
                      } catch (Exception e) {
                          
                          JOptionPane.showMessageDialog(null, e);
                      }
                      
                   
                      
                  }

              }
              
               if(choosereport.getSelectedIndex()==4){
                 
                  JFileChooser dialog = new JFileChooser();
                  dialog.setSelectedFile(new File("Employees SalaryDeduction Full Report"+".pdf"));
                  
                  int dialogResult = dialog.showSaveDialog(null);
                  
                  if(dialogResult == JFileChooser.APPROVE_OPTION){
                      
                      String filepath = dialog.getSelectedFile().getPath();
                      
                      try {
                          
                          String sql = "SELECT * FROM `salarydeduction`";
                         
                          pst = conn.prepareCall(sql);
                          rs = pst.executeQuery();
                                              
                          
                          Document mydoc = new Document();
                          PdfWriter myWriter = PdfWriter.getInstance(mydoc, new FileOutputStream(filepath));
                          PdfPTable table = new PdfPTable(10);
                          
                          mydoc.open();
                          
                          float[] ColumnWidth = new float[]{9,7,7,6,8,7,5,6,8,9};
                          table.setWidths(ColumnWidth);
                          table.setWidthPercentage(100);
                          
                          
                          mydoc.add(new Paragraph("Employee SalaryDeduction Full Report",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          mydoc.add(new Paragraph(new Date().toString(),FontFactory.getFont(FontFactory.TIMES_BOLD,17,Font.BOLD)));
                          mydoc.add(new Paragraph(" ",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          mydoc.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                          mydoc.add(new Paragraph(" ",FontFactory.getFont(FontFactory.TIMES_BOLD,20,Font.BOLD)));
                          
                          table.addCell(new PdfPCell(new Paragraph("Employeeid",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Firstname",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Surname",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Department",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Salary",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Dste",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("Percent/Amount",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD)))); 
                          table.addCell(new PdfPCell(new Paragraph("TotalIncrease",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Newsalary",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                          table.addCell(new PdfPCell(new Paragraph("Reason",FontFactory.getFont(FontFactory.TIMES_ROMAN,9,Font.BOLD))));
                           
                          while(rs.next()){
                              
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(1),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));    
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(2),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(3),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(4),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(5),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(6),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(7),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(8),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(9),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                          table.addCell(new PdfPCell(new Paragraph(rs.getString(10),FontFactory.getFont(FontFactory.TIMES_ROMAN,8,Font.NORMAL))));
                       
                          }
                          
                          
                          
                          mydoc.add(table);
                          
                          mydoc.add(new Paragraph("------------------------------------------------------------------"
                         + "----------",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
                          
                          mydoc.close();
                          
                          JOptionPane.showMessageDialog(null, "Report Generated Successfully");
                          
                          
                      } catch (Exception e) {
                          
                          JOptionPane.showMessageDialog(null, e);
                      }
                      
                   
                      
                  }

              }
            
            
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
        
      
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choosereport;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
