/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PayRollSystem;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import sun.java2d.pipe.SpanShapeRenderer;

/**
 *
 * @author albertzkiki
 */
public class Salaries extends javax.swing.JInternalFrame {

    /**
     * Creates new form Salaries
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement stm = null;
    
    public Salaries() {
        initComponents();
         datecalendar();
         datecalendar2();
    
    }
    
  public void datecalendar(){
      
     Calendar time = Calendar.getInstance();
    time.getTime();
    
    SimpleDateFormat dat = new SimpleDateFormat(" "+"E"+" "+"/"+" "+"dd"+" "+"/"+" "+"mm"+" "+"/"+" "+"yyyy");
    date.setText(dat.format(time.getTime()));
  }
  
    public void clear(){
        
         firstname.setText("");
        surname.setText("");
        department.setText("");
        basicsalary.setText("");
        percentage.setText("");
        amount.setText("");
        updatesalary.setSelectedIndex(0);
        employeeid.setText("");
        reason.setText("");
        totalincrease.setText("0.00");
        newsalary.setText("0.00");
        datecalendar();
      
    }
    
     public void clear1(){
        
         firstname2.setText("");
        surname2.setText("");
        department2.setText("");
        basicsalary2.setText("");
        percentage2.setText("");
        amount2.setText("");
        updatesalary2.setSelectedIndex(0);
        employeeid2.setText("");
        reason2.setText("");
        totaldeduction2.setText("0.00");
        newsalary2.setText("0.00");
        datecalendar2();
      
    }
     
     public void datecalendar2(){
         
         Calendar timer = Calendar.getInstance();
         timer.getTime();
         
         SimpleDateFormat dat = new SimpleDateFormat(" "+"E"+" "+" dd"+" "+"/"+" "+"mm"+" "+"/"+" "+"yyyy");
         date2.setText(dat.format(timer.getTime()));
         
         
     }
    
    
    
    public void updateSave(String QUERRY) {
        try {
            
            connection connect = new connection();
            conn = (Connection)connect.Connectdb();
            pst = conn.prepareStatement(QUERRY);
            pst.execute();
            //conn.close();
            
        } catch (SQLException e) {
            
          JOptionPane.showMessageDialog(null, e);
          
        }

   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        employeeid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        department = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        basicsalary = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        updatesalary = new javax.swing.JComboBox<>();
        percentage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        totalincrease = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        newsalary = new javax.swing.JLabel();
        calaculate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reason = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        employeeid2 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        firstname2 = new javax.swing.JTextField();
        surname2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        department2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        basicsalary2 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        updatesalary2 = new javax.swing.JComboBox<>();
        percentage2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        amount2 = new javax.swing.JTextField();
        save1 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        clear2 = new javax.swing.JButton();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        totaldeduction2 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        newsalary2 = new javax.swing.JLabel();
        calaculate1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        reason2 = new javax.swing.JTextArea();
        jLabel44 = new javax.swing.JLabel();
        date2 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);

        jTabbedPane1.setBackground(getBackground());
        jTabbedPane1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "Salaries", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Increase");

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("EmployeeID :");

        employeeid.setBackground(getBackground());
        employeeid.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        employeeid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        employeeid.setBorder(null);
        employeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeidActionPerformed(evt);
            }
        });
        employeeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                employeeidKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("(Press enter after inserting the employee id)");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Surname:");

        firstname.setEditable(false);
        firstname.setBackground(getBackground());
        firstname.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstname.setBorder(null);
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        surname.setEditable(false);
        surname.setBackground(getBackground());
        surname.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        surname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        surname.setBorder(null);
        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Department:");

        department.setEditable(false);
        department.setBackground(getBackground());
        department.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        department.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        department.setBorder(null);
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Basic Salary:");

        basicsalary.setEditable(false);
        basicsalary.setBackground(getBackground());
        basicsalary.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        basicsalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        basicsalary.setBorder(null);
        basicsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicsalaryActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Update Salary By :");

        updatesalary.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        updatesalary.setForeground(new java.awt.Color(255, 255, 255));
        updatesalary.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select One--", "Percentage", "Amount" }));
        updatesalary.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updatesalaryItemStateChanged(evt);
            }
        });
        updatesalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatesalaryActionPerformed(evt);
            }
        });

        percentage.setBackground(getBackground());
        percentage.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        percentage.setForeground(new java.awt.Color(255, 255, 255));
        percentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentage.setBorder(null);
        percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageActionPerformed(evt);
            }
        });
        percentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                percentageKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Percentage(%)");

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Amount:");

        amount.setBackground(getBackground());
        amount.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount.setBorder(null);
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountKeyReleased(evt);
            }
        });

        save.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        save.setText("Update");
        save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salary_1.png"))); // NOI18N

        clear.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        clear.setText("Clear Search");
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Reason:");

        jLabel24.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Total Increase:");

        totalincrease.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        totalincrease.setForeground(new java.awt.Color(255, 255, 255));
        totalincrease.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalincrease.setText("0.00");

        jLabel26.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("New Salary:");

        newsalary.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        newsalary.setForeground(new java.awt.Color(255, 255, 255));
        newsalary.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newsalary.setText("0.00");

        calaculate.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        calaculate.setText("Calculate");
        calaculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calaculateActionPerformed(evt);
            }
        });

        reason.setBackground(getBackground());
        reason.setColumns(20);
        reason.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        reason.setForeground(new java.awt.Color(255, 255, 255));
        reason.setRows(5);
        jScrollPane2.setViewportView(reason);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Date:");

        date.setEditable(false);
        date.setBackground(getBackground());
        date.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setBorder(null);
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(employeeid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(firstname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(surname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(department, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(basicsalary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(updatesalary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(percentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(amount, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(save, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(totalincrease, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(newsalary, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(calaculate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(date, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addComponent(employeeid, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(surname, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(department, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(basicsalary)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(72, 72, 72)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(updatesalary, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(percentage))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalincrease, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calaculate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator7)
                                    .addComponent(amount))
                                .addGap(67, 67, 67)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeid))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(basicsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(updatesalary)
                    .addComponent(jLabel12)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalincrease, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(calaculate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(save))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Increase Salary", jDesktopPane1);

        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "Salaries", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Deduction");

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("EmployeeID :");

        employeeid2.setBackground(getBackground());
        employeeid2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        employeeid2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        employeeid2.setBorder(null);
        employeeid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeid2ActionPerformed(evt);
            }
        });
        employeeid2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                employeeid2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                employeeid2KeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("(Press enter after inserting the employee id)");

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("First Name:");

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Surname:");

        firstname2.setEditable(false);
        firstname2.setBackground(getBackground());
        firstname2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        firstname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstname2.setBorder(null);
        firstname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname2ActionPerformed(evt);
            }
        });

        surname2.setEditable(false);
        surname2.setBackground(getBackground());
        surname2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        surname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        surname2.setBorder(null);
        surname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surname2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Department:");

        department2.setEditable(false);
        department2.setBackground(getBackground());
        department2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        department2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        department2.setBorder(null);
        department2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Basic Salary:");

        basicsalary2.setEditable(false);
        basicsalary2.setBackground(getBackground());
        basicsalary2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        basicsalary2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        basicsalary2.setBorder(null);
        basicsalary2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicsalary2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Bauhaus 93", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Update Salary By :");

        updatesalary2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        updatesalary2.setForeground(new java.awt.Color(255, 255, 255));
        updatesalary2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select One--", "Percentage", "Amount" }));
        updatesalary2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updatesalary2ItemStateChanged(evt);
            }
        });
        updatesalary2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatesalary2ActionPerformed(evt);
            }
        });

        percentage2.setBackground(getBackground());
        percentage2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        percentage2.setForeground(new java.awt.Color(255, 255, 255));
        percentage2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        percentage2.setBorder(null);
        percentage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentage2ActionPerformed(evt);
            }
        });
        percentage2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                percentage2KeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Percentage(%)");

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Amount:");

        amount2.setBackground(getBackground());
        amount2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        amount2.setForeground(new java.awt.Color(255, 255, 255));
        amount2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount2.setBorder(null);
        amount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount2ActionPerformed(evt);
            }
        });
        amount2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amount2KeyReleased(evt);
            }
        });

        save1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        save1.setText("Update");
        save1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salary_1.png"))); // NOI18N

        clear2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        clear2.setText("Clear Search");
        clear2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("Reason:");

        jLabel42.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("Total Deduction:");

        totaldeduction2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        totaldeduction2.setForeground(new java.awt.Color(255, 255, 255));
        totaldeduction2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totaldeduction2.setText("0.00");

        jLabel43.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("New Salary:");

        newsalary2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        newsalary2.setForeground(new java.awt.Color(255, 255, 255));
        newsalary2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newsalary2.setText("0.00");

        calaculate1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        calaculate1.setText("Calculate");
        calaculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calaculate1ActionPerformed(evt);
            }
        });

        reason2.setBackground(getBackground());
        reason2.setColumns(20);
        reason2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        reason2.setForeground(new java.awt.Color(255, 255, 255));
        reason2.setRows(5);
        jScrollPane3.setViewportView(reason2);

        jLabel44.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("Date:");

        date2.setEditable(false);
        date2.setBackground(getBackground());
        date2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        date2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date2.setBorder(null);
        date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2ActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(employeeid2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jSeparator9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(firstname2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(surname2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(department2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(basicsalary2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jSeparator10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jSeparator11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jSeparator12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jSeparator13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(updatesalary2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(percentage2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jSeparator14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(amount2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(save1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(clear2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jSeparator22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(totaldeduction2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel43, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(newsalary2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(calaculate1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel44, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(date2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jSeparator23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator9)
                                .addComponent(employeeid2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator23, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(jSeparator13, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstname2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(surname2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(department2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(basicsalary2)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(date2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(72, 72, 72)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(updatesalary2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator14, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(percentage2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newsalary2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totaldeduction2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67)
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calaculate1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator22)
                                    .addComponent(amount2))
                                .addGap(67, 67, 67)
                                .addComponent(clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeid2))
                .addGap(0, 0, 0)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(firstname2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(surname2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(department2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(basicsalary2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(updatesalary2)
                    .addComponent(jLabel44)
                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(percentage2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(amount2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totaldeduction2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(calaculate1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newsalary2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(save1))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Deduction", jDesktopPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeidActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void basicsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicsalaryActionPerformed

    private void percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentageActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       
            try {
                
                if(firstname.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "No details to be saved","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(percentage.getText().equals("") || amount.getText().equals("")){
                     JOptionPane.showMessageDialog(this, "No Increase has been made","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(reason.getText().equals("")){
                     JOptionPane.showMessageDialog(this, "Please enter a a valid reason","Error",JOptionPane.ERROR_MESSAGE);
                    return;  
                }
                
            connection connect = new connection();
            conn = (Connection)connect.Connectdb();
            try {
                
                int  a = JOptionPane.showConfirmDialog(null, "Are you Sure you want to save","Add Record",JOptionPane.YES_NO_OPTION);
        
                if (a == 0) {
            
            String bsalary = basicsalary.getText();
            String employeeids = employeeid.getText();
            
            
            String sql4="INSERT INTO `salaryincrease`(`Employeeid`,`Firstname`,`Surname`,`Department`,`Salary`,`Date`"
                    + ",`TotalIncrease`,`Newsalary`,`Reason`)VALUES('"+employeeid.getText()+"','"+firstname.getText()+"',"
                    + "'"+surname.getText()+"','"+department.getText()+"','"+basicsalary.getText()+"','"+date.getText()+"',"
                    + "'"+totalincrease.getText()+"','"+newsalary.getText()+"','"+reason.getText()+"')";
            
                    
                    
                    String sql3 = "UPDATE `employeeregistartion` SET `Salary` = '"+newsalary.getText()+"' WHERE `Employeeid` ='"+employeeids+"' ";
                    updateSave(sql3);
                    
                    pst = conn.prepareStatement(sql4);
                    pst.execute();
            
                    JOptionPane.showMessageDialog(this,"Record updated successfully","Messsage",JOptionPane.INFORMATION_MESSAGE);
                }
                
            }catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
            }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
            
            }
        
    }//GEN-LAST:event_saveActionPerformed

    private void updatesalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatesalaryActionPerformed
        
    }//GEN-LAST:event_updatesalaryActionPerformed

    private void updatesalaryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_updatesalaryItemStateChanged
       
       int update = updatesalary.getSelectedIndex();
       
       if (update == 0){
           
           percentage.setEditable(false);
           amount.setEditable(false);
           percentage.setEnabled(false);
           amount.setEnabled(false);
           percentage.setText("");
           amount.setText("");
           
       }
       else if(update == 1){
           
           percentage.setEditable(true);
           percentage.setEnabled(true);
           amount.setText("Deactivated");
           amount.setEditable(false);
           amount.setEnabled(false);
           percentage.setText("");
       }
       else{
           
           percentage.setText("Deactivated");
           amount.setEnabled(true);
           percentage.setEditable(false);
           amount.setEditable(true);
           percentage.setEnabled(false);
           amount.setText("");
           
       }
       
    }//GEN-LAST:event_updatesalaryItemStateChanged

    private void employeeidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeidKeyReleased
       
         connection connect = new connection();
        conn = (Connection)connect.Connectdb();
        
        try{
            
        String sql = "SELECT * FROM `employeeregistartion` WHERE employeeid='"+employeeid.getText()+"'";
        
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        if(rs.next()){
          
        String fname = rs.getString("Firstname");
        String sname = rs.getString("Surname");
        String dept =rs.getString("Department");
        String salary = rs.getString("Salary");
        
        firstname.setText(fname);
        surname.setText(sname);
        department.setText(dept);
        basicsalary.setText(salary);
        
          
        }
        
       
        }catch(Exception e){
       
            JOptionPane.showMessageDialog(null, e);
        
        }    
        
        
    }//GEN-LAST:event_employeeidKeyReleased

    private void employeeidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeidKeyPressed
      
//        int length = employeeid.getText().length();
//        
//        if (length == 14){
        
       
//        }
        
        
    }//GEN-LAST:event_employeeidKeyPressed

    private void percentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percentageKeyReleased
       
        char c = evt.getKeyChar();
        
        if(!((c>='0' && c<='9') || (c == KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            
            getToolkit().beep();
            evt.consume();
            percentage.setText("");
            JOptionPane.showMessageDialog(this, "Enter Numerics Only","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_percentageKeyReleased

    private void amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyReleased
       
        char c = evt.getKeyChar();
        
        if(!((c>='0' && c<='9') || (c == KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            
            getToolkit().beep();
            evt.consume();
            amount.setText("");
            JOptionPane.showMessageDialog(this, "Enter Numerics Only","WARNING",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_amountKeyReleased

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

       clear();

    }//GEN-LAST:event_clearActionPerformed

    private void calaculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calaculateActionPerformed
        
        int salary = Integer.parseInt(basicsalary.getText());
        int update = updatesalary.getSelectedIndex();
        
        if (update == 1){
          
        int percent = Integer.parseInt(percentage.getText());
        int calculate = salary/100 * percent;
        String TI = String.valueOf(calculate);
        totalincrease.setText(TI);
        int NS = calculate + salary;
        String newsalo = String.valueOf(NS);
        newsalary.setText(newsalo);
        
        
        }    
        else if(update == 2){
        int ByAmount = Integer.parseInt(amount.getText());
        int Calc = salary + ByAmount;
        String NewAmount = String.valueOf(Calc);
        newsalary.setText(NewAmount);
        totalincrease.setText(amount.getText());
        
        }  
        
      
        
    }//GEN-LAST:event_calaculateActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void employeeid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeid2ActionPerformed

    private void employeeid2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeid2KeyPressed
       
        char c = evt.getKeyChar();
        
        if(c==KeyEvent.VK_ENTER){
       
        connection connect = new connection();
        conn = (Connection)connect.Connectdb();
        
        try{
            
            String sql5 = "Select * FROM `employeeregistartion` WHERE Employeeid='"+employeeid2.getText()+"'";
            pst = conn.prepareStatement(sql5);
            rs = pst.executeQuery();
            
            if(rs.next()){
                
                String fname = rs.getString("Firstname");
                String sname = rs.getString("Surname");
                String dept = rs.getString("Department");
                String bsalary = rs.getString("Salary");
                
                firstname2.setText(fname);
                surname2.setText(sname);
                department2.setText(dept);
                basicsalary2.setText(bsalary);
                
                
                
                
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        }
    }//GEN-LAST:event_employeeid2KeyPressed

    private void employeeid2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeid2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeid2KeyReleased

    private void firstname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname2ActionPerformed

    private void surname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surname2ActionPerformed

    private void department2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_department2ActionPerformed

    private void basicsalary2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicsalary2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basicsalary2ActionPerformed

    private void updatesalary2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_updatesalary2ItemStateChanged
       
       int updateby = updatesalary2.getSelectedIndex();
       
       if(updateby == 0){
           
           percentage2.setEditable(false);
           percentage2.setEnabled(false);
           amount2.setEditable(false);
           amount2.setEnabled(false);
           percentage2.setText("");
           amount2.setText("");
           
       }
       if(updateby == 1){
           percentage2.setEditable(true);
           percentage2.setEnabled(true);
           amount2.setEditable(false);
           amount2.setEnabled(false);
           percentage2.setText("");
           amount2.setText("Deactivated");
          
       }
       if(updateby == 2){
           percentage2.setEditable(false);
           percentage2.setEnabled(false);
           amount2.setEditable(true);
           amount2.setEnabled(true);
           percentage2.setText("Deactivated");
           amount2.setText("");
          
       }
       
        
    }//GEN-LAST:event_updatesalary2ItemStateChanged

    private void updatesalary2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatesalary2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatesalary2ActionPerformed

    private void percentage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentage2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentage2ActionPerformed

    private void percentage2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_percentage2KeyReleased
        
        char c = evt.getKeyChar();
        
        if(!((c>='0' && c<='9') || (c==KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_ENTER) || (c==KeyEvent.VK_DELETE))){
            
            getToolkit().beep();
            evt.consume();
            employeeid.setText(" ");
            JOptionPane.showMessageDialog(null, "Enter numerics only");
            
        }
        
    }//GEN-LAST:event_percentage2KeyReleased

    private void amount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount2ActionPerformed

    private void amount2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amount2KeyReleased
      
        char c = evt.getKeyChar();
        
        if(!((c>='0' && c<='9') || (c==KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_ENTER) || (c==KeyEvent.VK_DELETE))){
            
            getToolkit().beep();
            evt.consume();
            employeeid.setText(" ");
            JOptionPane.showMessageDialog(null, "Enter numerics only");
            
        }
        
    }//GEN-LAST:event_amount2KeyReleased

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
         try {
                
                if(firstname2.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "No details to be saved","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(percentage2.getText().equals("") || amount2.getText().equals("")){
                     JOptionPane.showMessageDialog(this, "No Deduction has been made","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(reason2.getText().equals("")){
                     JOptionPane.showMessageDialog(this, "Please enter a a valid reason","Error",JOptionPane.ERROR_MESSAGE);
                    return;  
                }
                
            connection connect = new connection();
            conn = (Connection)connect.Connectdb();
            try {
                
                int  a = JOptionPane.showConfirmDialog(null, "Are you Sure you want to save","Add Record",JOptionPane.YES_NO_OPTION);
        
                if (a == 0) {
            
            String bsalary = basicsalary.getText();
            String employeeids = employeeid.getText();
            
            
            String sql4="INSERT INTO `salarydeduction`(`Employeeid`,`Firstname`,`Surname`,`Department`,`Salary`,`Date`"
                    + ",`TotalDeduction`,`Newsalary`,`Reason`)VALUES('"+employeeid2.getText()+"','"+firstname2.getText()+"',"
                    + "'"+surname2.getText()+"','"+department2.getText()+"','"+basicsalary2.getText()+"','"+date2.getText()+"',"
                    + "'"+totaldeduction2.getText()+"','"+newsalary2.getText()+"','"+reason2.getText()+"')";
            
                    
                    
                    String sql3 = "UPDATE `employeeregistartion` SET `Salary` = '"+newsalary.getText()+"' WHERE `Employeeid` ='"+employeeids+"' ";
                    updateSave(sql3);
                    
                    pst = conn.prepareStatement(sql4);
                    pst.execute();
            
                    JOptionPane.showMessageDialog(this,"Record updated successfully","Messsage",JOptionPane.INFORMATION_MESSAGE);
                }
                
            }catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
            
        }
            }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
            
            }
        
    }//GEN-LAST:event_save1ActionPerformed

    private void clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2ActionPerformed
        clear1();
    }//GEN-LAST:event_clear2ActionPerformed

    private void calaculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calaculate1ActionPerformed
        
        int salary = Integer.parseInt(basicsalary2.getText());
       
        int updateby = updatesalary2.getSelectedIndex();
        
        
        if(updateby == 1){
            
            int percent = Integer.parseInt(percentage2.getText());
            int calc = salary/100 * percent;
            String a = String.valueOf(calc);
        
            totaldeduction2.setText(a);
            int total =salary-calc;
            String b = String.valueOf(total);
            newsalary2.setText(b);
        }
        else if(updateby == 2){
            
            int amount1 =  Integer.parseInt(amount2.getText());
            int x =salary-amount1;
            String c = String.valueOf(x);
            totaldeduction2.setText(amount2.getText());
            newsalary2.setText(c);
            
        }
        
        
    }//GEN-LAST:event_calaculate1ActionPerformed

    private void date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amount2;
    private javax.swing.JTextField basicsalary;
    private javax.swing.JTextField basicsalary2;
    private javax.swing.JButton calaculate;
    private javax.swing.JButton calaculate1;
    private javax.swing.JButton clear;
    private javax.swing.JButton clear2;
    private javax.swing.JTextField date;
    private javax.swing.JTextField date2;
    private javax.swing.JTextField department;
    private javax.swing.JTextField department2;
    private javax.swing.JTextField employeeid;
    private javax.swing.JTextField employeeid2;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField firstname2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel newsalary;
    private javax.swing.JLabel newsalary2;
    private javax.swing.JTextField percentage;
    private javax.swing.JTextField percentage2;
    private javax.swing.JTextArea reason;
    private javax.swing.JTextArea reason2;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField surname2;
    private javax.swing.JLabel totaldeduction2;
    private javax.swing.JLabel totalincrease;
    private javax.swing.JComboBox<String> updatesalary;
    private javax.swing.JComboBox<String> updatesalary2;
    // End of variables declaration//GEN-END:variables
}
